- method: GET
  uri: /xml
  example: /xml
  statusCode: 200
  body: |
    <?xml version="1.0" encoding="UTF-8"?>
    <movies>
      <movie name="Shutter Island">
        <director firstName="Martin" lastName="Scorsese" />
      </movie>
      <movie name="Kill Bill II">
        <director firstName="Quentin" lastName="Tarantino" />
      </movie>
    </movies>
  bodyContentType: text/xml

- method: GET
  uri: /jsonNested
  example: /jsonNested
  statusCode: 200
  body: |
    {
      "movies": [
        {
          "name": "Shutter Island",
          "director": {
            "firstName": "Martin",
            "lastName": "Scorsese"
          }
        },
        {
          "name": "Kill Bill II",
          "director": {
            "firstName": "Quentin",
            "lastName": "Tarantino"
          }
        }
      ]
    }
  bodyContentType: application/json

- method: GET
  uri: /jsonArray
  example: /jsonArray
  statusCode: 200
  body: |
    [
      {
        "name": "Shutter Island",
        "director": {
          "firstName": "Martin",
          "lastName": "Scorsese"
        }
      },
      {
        "name": "Kill Bill II",
        "director": {
          "firstName": "Quentin",
          "lastName": "Tarantino"
        }
      }
    ]
  bodyContentType: application/json

- method: GET
  uri: /person/:name/:age
  example: /person/Rob/31
  statusCode: 200
  body: 'Name: {{.name}} Age: {{.age}}'

- method: GET
  uri: /timeout/:duration
  example: /timeout/1s
  statusCode: 200
  durationArg: duration

- method: GET
  uri: /error
  example: /error
  statusCode: 500